### ISSUE TITLE
imageLoad.imageLoader class exception, i dont know how to setup path

### ISSUE THREAD

**Issue by Megalunchbox** [Megalunchbox/2DGameProject#4]
Heres the exception for those who need it...

Exception in thread "main" java.lang.IllegalArgumentException: input == null!
	at javax.imageio.ImageIO.read(ImageIO.java:1388)
	at textures.ImageLoad.imageLoader(ImageLoad.java:17)
	at game.Game.init(Game.java:84)
	at game.Game.run(Game.java:96)
	at game.Game.startThread(Game.java:33)
	at launcher.Main.main(Main.java:15)

and heres my tree

![tree](https://user-images.githubusercontent.com/25992577/29950808-cc3b9288-8e83-11e7-9432-6e188e952a90.PNG)

that should explain, i need to figure out the <code>imageLoader(path);</code>

so i thought it was 

<code> imageLoader("textures/sky.png"); </code> which i believe should work, but it doesn't...
so if someone could help me on that error it would be great as im done for now, until i get this error sorted out.

**Comment by DaMatrix** [comment]
1) use IntelliJ, it's better.
2) put all your packages inside a main package (like `com.megalunchbox.textures.ImageLoad`), it's good practice.
3) (also the answer to your question) you don't put your resources in the same package as your `ImageLoad` class, but in the default package (or `src/main/resources` if you're using Maven/Gradle, which you should be for any sort of project like this)

**Comment by Megalunchbox** [comment]
thanks
